In [1]:
def CharChange(str):
    char = str[0]
    str = str.replace(char,'$')
    str =  char+str[1:]
    return str

CharChange('prospect')
    

'pros$ect'

In [2]:
def chars_mix_up(a, b):
    new_a = b[:2] + a[2:]
    new_b = a[:2] + b[2:]
    return new_a + ' ' + new_b
print(chars_mix_up('abc', 'xyz'))


xyc abz


In [3]:
def add_string(str1):
    length = len(str1)
    if length > 2:
        if str1[-3:] == 'ing':
            str1 += 'ly'
        else:
            str1 += 'ing'
    return str1
print(add_string('ab'))
print(add_string('abc'))
print(add_string('string'))

ab
abcing
stringly


In [4]:
def not_poor(str1):
    snot = str1.find('not')
    spoor = str1.find('poor')
    if spoor > snot and snot>0 and spoor>0:
        str1 = str1.replace(str1[snot:(spoor+4)], 'good')
        return str1
    else:
        return str1
print(not_poor('The lyrics are not that poor!'))
print(not_poor('The lyrics are poor!'))

The lyrics are good!
The lyrics are poor!


In [5]:
def odd_values_string(str):
    result = ""
    for i in range(len(str)):
        if i % 2 == 0:
            result = result + str[i]
    return result
print(odd_values_string('abcdef'))
print(odd_values_string('python'))

ace
pto


In [6]:
def insert_end(str):
    sub_str = str[-2:] 
    return sub_str * 4 
print(insert_end('Python')) 
print(insert_end('Exercises'))

onononon
eseseses


In [7]:
def first_three(str): 
    return str[:3] if len(str) > 3 else str
print(first_three('ipy')) 
print(first_three('python')) 

ipy
pyt


In [8]:
x = 3.1415926
y = 12.9999
print("\nOriginal Number: ", x) 
print("Formatted Number: "+"{:.2f}".format(x)); 
print("Original Number: ", y) 
print("Formatted Number: "+"{:.2f}".format(y));
print()


Original Number:  3.1415926
Formatted Number: 3.14
Original Number:  12.9999
Formatted Number: 13.00



In [9]:
x = 0.25 
y = -0.25 
print("\nOriginal Number: ", x) 
print("Formatted Number with percentage: "+"{:.2%}".format(x)); 
print("Original Number: ", y) 
print("Formatted Number with percentage: "+"{:.2%}".format(y));


Original Number:  0.25
Formatted Number with percentage: 25.00%
Original Number:  -0.25
Formatted Number with percentage: -25.00%


In [10]:
str1 = 'The quick brown fox jumps over the lazy dog.'
print(str1.count("fox"))

1


In [11]:
import collections 
str1 = 'thequickbrownfoxjumpsoverthelazydog' 
d = collections.defaultdict(int) 
for c in str1:
    d[c] += 1
for c in sorted(d, key=d.get, reverse=True): 
    if d[c] > 1:
        print('%s %d' % (c, d[c]))

o 4
e 3
t 2
h 2
u 2
r 2


In [12]:
area = 1256.66 
volume = 1254.725 
decimals = 2 
print("The area of the rectangle is {0:.{1}f}cm\u00b2".format(area, decimals)) 
decimals = 3 
print("The volume of the cylinder is {0:.{1}f}cm\u00b3".format(volume, decimals))

The area of the rectangle is 1256.66cm²
The volume of the cylinder is 1254.725cm³


In [13]:
import string 
alphabet = set(string.ascii_lowercase) 
input_string = 'The quick brown fox jumps over the lazy dog' 
print(set(input_string.lower()) >= alphabet)
input_string = 'The quick brown fox jumps over the lazy cat'
print(set(input_string.lower()) >= alphabet)

True
False


In [14]:
def word_count(str):
    counts = dict()
    words = str.split()
    for word in words: 
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
        counts_x = sorted(counts.items(), key=lambda kv: kv[1])
    
    return counts_x[-2]
print(word_count("Python is easy and supports many libraries, it is useful in data science but it is slow "))

('it', 2)


In [15]:
import collections
def min_window(str1, str2): 
    result_char, missing_char = collections.Counter(str2),len(str2) 
    i = p = q = 0 
    for j, c in enumerate(str1, 1): 
        missing_char -= result_char[c] > 0 
        result_char[c] -= 1 
        if not missing_char: 
            while i < q and result_char[str1[i]] < 0: 
                result_char[str1[i]] += 1 
                i += 1 
            if not q or j - i <= q - p: 
                p, q = i, j 
    return str1[p:q]
str1 = "PRWSOERIUSFK"
str2 = "OSU"
print("Original Strings:\n",str1,"\n",str2)
print("Minimum window:")
print(min_window(str1,str2))

Original Strings:
 PRWSOERIUSFK 
 OSU
Minimum window:
OERIUS


In [16]:
from collections import defaultdict
def find_sub_string(str): 
    str_len = len(str)
# Count all distinct characters. 
    dist_count_char = len(set([x for x in str]))

    ctr, start_pos, start_pos_index, min_len = 0, 0, -1, 9999999999 
    curr_count = defaultdict(lambda: 0) 
    for i in range(str_len): 
        curr_count[str[i]] += 1
        if curr_count[str[i]] == 1: 
            ctr += 1
            if ctr == dist_count_char: 
                while curr_count[str[start_pos]] > 1: 
                    if curr_count[str[start_pos]] > 1:
                        curr_count[str[start_pos]] -= 1 
                    start_pos += 1
                len_window = i - start_pos + 1 

                if min_len > len_window:
                    min_len = len_window 
                    start_pos_index = start_pos 
    return str[start_pos_index: start_pos_index + min_len]

str1 = "asdaewsqgtwwsa"
print("Original Strings:\n",str1)
print("\nSmallest window that contains all characters of the said string:") 
print(find_sub_string(str1))

Original Strings:
 asdaewsqgtwwsa

Smallest window that contains all characters of the said string:
daewsqgt


In [17]:
def count_k_dist(str1, k):
    str_len = len(str1) 
    result = 0
    ctr = [0] * 27
    for i in range(0, str_len): 
        dist_ctr = 0
        ctr = [0] * 27
        for j in range(i, str_len): 
            if(ctr[ord(str1[j]) - 97] == 0): 
                dist_ctr += 1
        ctr[ord(str1[j]) - 97] += 1
        if(dist_ctr == k): 
            result += 1 
        if(dist_ctr > k): 
            break
    return result
str1 = input("Input a string (lowercase alphabets):")
k = int(input("Input k: "))
print("Number of substrings with exactly", k, "distinct characters : ", end = "") 
print(count_k_dist(str1, k))

Input a string (lowercase alphabets):wolf
Input k: 4
Number of substrings with exactly 4 distinct characters : 1


In [18]:
def number_of_substrings(str): 
    str_len = len(str); 
    return int(str_len * (str_len + 1) / 2);
str1 = input("Input a string: ")
print("Number of substrings:")
print(number_of_substrings(str1))

Input a string: w3resources
Number of substrings:
66


In [19]:
def no_of_substring_with_equalEnds(str1): 
    result = 0; 
    n = len(str1); 
    for i in range(n): 
        for j in range(i, n): 
            if (str1[i] == str1[j]): 
                result = result + 1 
    return result 
str1 = input("Input a string: ") 
print(no_of_substring_with_equalEnds(str1))

Input a string: abcd
4


In [20]:
def match_words(words): 
    ctr = 0
    for word in words: 
        if len(word) > 1 and word[0] == word[-1]: 
            ctr += 1 
    return ctr
print(match_words(['abc', 'xyz', 'aba', '1221']))

2


In [21]:
def last(n): 
    return n[-1]
def sort_list_last(tuples):
    return sorted(tuples, key=last)
print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [22]:
a = [10,20,30,20,10,50,60,40,80,50,40]

dup_items = set() 
uniq_items = [] 
for x in a: 
    if x not in dup_items: 
        uniq_items.append(x) 
        dup_items.add(x) 
print(dup_items)

{40, 10, 80, 50, 20, 60, 30}


In [23]:
def long_words(n, str): 
    word_len = []
    txt = str.split(" ")
    for x in txt: 
        if len(x) > n:
            word_len.append(x) 
    return word_len 
print(long_words(3, "The quick brown fox jumps over the lazy dog"))

['quick', 'brown', 'jumps', 'over', 'lazy']


In [24]:
color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow'] 
color = [x for (i,x) in enumerate(color) if i not in (0,4,5)]
print(color)

['Green', 'White', 'Black']


In [25]:
import itertools
print(list(itertools.permutations([1,2,3])))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [26]:
L = [(1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10)] 
print("Original List: ", L) 
print("Sorted Unique Data:",sorted(set().union(*L)))

Original List:  [(1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10)]
Sorted Unique Data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
class py_solution:
    def int_to_Roman(self, num): 
        val = [ 1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1 ] 
        syb = [ "M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I" ] 
        roman_num = '' 
        i = 0 
        while num > 0:
            for _ in range(num // val[i]):
                roman_num += syb[i]
                num -= val[i] 
            i += 1 
        return roman_num
print(py_solution().int_to_Roman(1)) 
print(py_solution().int_to_Roman(4000))

I
MMMM


In [28]:
class py_solution: 
    def roman_to_int(self, s): 
        rom_val = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
        int_val = 0 
        for i in range(len(s)):
            if i > 0 and rom_val[s[i]] > rom_val[s[i - 1]]: 
                int_val += rom_val[s[i]] - 2 * rom_val[s[i - 1]] 
            else: 
                int_val += rom_val[s[i]] 
        return int_val
print(py_solution().roman_to_int('MMMCMLXXXVI')) 
print(py_solution().roman_to_int('MMMM')) 
print(py_solution().roman_to_int('C'))

3986
4000
100


In [29]:
class py_solution: 
    def is_valid_parenthese(self, str1):
        stack, pchar = [], {"(": ")", "{": "}", "[": "]"} 
        for parenthese in str1: 
            if parenthese in pchar: 
                stack.append(parenthese)
            elif len(stack) == 0 or pchar[stack.pop()] != parenthese:
                return False 
        return len(stack) == 0 
print(py_solution().is_valid_parenthese("(){}[]")) 
print(py_solution().is_valid_parenthese("()[{)}")) 
print(py_solution().is_valid_parenthese("()"))

True
False
True


In [30]:
class py_solution: 
    def sub_sets(self, sset): 
        return self.subsetsRecur([], sorted(sset))
    def subsetsRecur(self, current, sset): 
        if sset: 
            return self.subsetsRecur(current, sset[1:]) + self.subsetsRecur(current + [sset[0]], sset[1:])
        return [current]
print(py_solution().sub_sets([4,5,6]))

[[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]]


In [31]:
class py_solution:
    def twoSum(self, nums, target):
        lookup = {} 
        for i, num in enumerate(nums):
            if target - num in lookup: 
                return (lookup[target - num], i )
            lookup[num] = i 
print("index1=%d, index2=%d" % py_solution().twoSum((10,20,10,40,50,60,70),50))

index1=2, index2=3


In [32]:
class py_solution:
 def threeSum(self, nums):
        nums, result, i = sorted(nums), [], 0
        while i < len(nums) - 2:
            j, k = i + 1, len(nums) - 1
            while j < k:
                if nums[i] + nums[j] + nums[k] < 0:
                    j += 1
                elif nums[i] + nums[j] + nums[k] > 0:
                    k -= 1
                else:
                    result.append([nums[i], nums[j], nums[k]])
                    j, k = j + 1, k - 1
                    while j < k and nums[j] == nums[j - 1]:
                        j += 1
                    while j < k and nums[k] == nums[k + 1]:
                        k -= 1
            i += 1
            while i < len(nums) - 2 and nums[i] == nums[i - 1]:
                i += 1
        return result

print(py_solution().threeSum([-25, -10, -7, -3, 2, 4, 8, 10]))


[[-10, 2, 8], [-7, -3, 10]]


In [33]:
class py_solution:
   def pow(self, x, n):
        if x==0 or x==1 or n==1:
            return x 

        if x==-1:
            if n%2 ==0:
                return 1
            else:
                return -1
        if n==0:
            return 1
        if n<0:
            return 1/self.pow(x,-n)
        val = self.pow(x,n//2)
        if n%2 ==0:
            return val*val
        return val*val*x

print(py_solution().pow(2, -3));
print(py_solution().pow(3, 5));
print(py_solution().pow(100, 0));


0.125
243
1


In [34]:
class IOString():
    def __init__(self):
        self.str1 = ""

    def get_String(self):
        self.str1 = input()

    def print_String(self):
        print(self.str1.upper())

str1 = IOString()
str1.get_String()
str1.print_String()


python
PYTHON


In [35]:
class Rectangle():
    def __init__(self, l, w):
        self.length = l
        self.width  = w

    def rectangle_area(self):
        return self.length*self.width

newRectangle = Rectangle(12, 10)
print(newRectangle.rectangle_area())


120


In [36]:
class Circle():
    def __init__(self, r):
        self.radius = r

    def area(self):
        return self.radius**2*3.14
    
    def perimeter(self):
        return 2*self.radius*3.14

NewCircle = Circle(8)
print(NewCircle.area())
print(NewCircle.perimeter())


200.96
50.24


In [37]:
class Circle():
    def __init__(self, r):
        self.radius = r

    def area(self):
        return self.radius**2*3.14
    
    def perimeter(self):
        return 2*self.radius*3.14

NewCircle = Circle(8)
print(NewCircle.area())
print(NewCircle.perimeter())


200.96
50.24


In [38]:
import itertools
x = itertools.cycle('ABCD')
print(type(x).__name__)


cycle


In [39]:
from collections import Counter
classes = (
    ('V', 1),
    ('VI', 1),
    ('V', 2),
    ('VI', 2),
    ('VI', 3),
    ('VII', 1),
)
students = Counter(class_name for class_name, no_students in classes)
print(students)


Counter({'VI': 3, 'V': 2, 'VII': 1})


In [40]:
from collections import OrderedDict
dict = {'Afghanistan': 93, 'Albania': 355, 'Algeria': 213, 'Andorra': 376, 'Angola': 244}
new_dict = OrderedDict(dict.items())
for key in new_dict:
    print (key, new_dict[key])

print("\nIn reverse order:")
for key in reversed(new_dict):
    print (key, new_dict[key])


Afghanistan 93
Albania 355
Algeria 213
Andorra 376
Angola 244

In reverse order:
Angola 244
Andorra 376
Algeria 213
Albania 355
Afghanistan 93


In [41]:
from collections import Counter
def compare_lists(x, y):
    return Counter(x) == Counter(y)
n1 = [20, 10, 30, 10, 20, 30]
n2 = [30, 20, 10, 30, 20, 50]
print(compare_lists(n1, n2))


False


In [42]:
from array import array
a = array("I", (12,25))
print("Array buffer start address in memory and number of elements.")
print(a.buffer_info())


Array buffer start address in memory and number of elements.
(2006617912352, 2)


In [46]:
from array import array 
a = array("I", (12,25))
print("Array buffer start address in memory and number of elements.") 
print(a.buffer_info())


Array buffer start address in memory and number of elements.
(2006617912768, 2)


In [45]:
import array 
import binascii 
a = array.array('i', [1,2,3,4,5,6]) 
print("Original array:") 
print('A1:', a) 
bytes_array = a.tobytes()
print('Array of bytes:', binascii.hexlify(bytes_array))

Original array:
A1: array('i', [1, 2, 3, 4, 5, 6])
Array of bytes: b'010000000200000003000000040000000500000006000000'


In [51]:
from array import array 
import binascii
array1 = array('i', [7, 8, 9, 10]) 
print('array1:', array1) 
as_bytes = array1.tobytes() 
print('Bytes:', binascii.hexlify(as_bytes)) 
array2 = array('i')
array2.frombytes(as_bytes) 
print('array2:', array2)

array1: array('i', [7, 8, 9, 10])
Bytes: b'0700000008000000090000000a000000'
array2: array('i', [7, 8, 9, 10])


In [52]:
import heapq
heap = []
heapq.heappush(heap, ('V', 3))
heapq.heappush(heap, ('V', 2))
heapq.heappush(heap, ('V', 1))
print("Items in the heap:")
for a in heap:
	print(a)
print("----------------------")
print("The smallest item in the heap:")
print(heap[0])
print("----------------------")
print("Pop the smallest item in the heap:")
heapq.heappop(heap)
for a in heap:
	print(a)


Items in the heap:
('V', 1)
('V', 3)
('V', 2)
----------------------
The smallest item in the heap:
('V', 1)
----------------------
Pop the smallest item in the heap:
('V', 2)
('V', 3)


In [53]:
import bisect
def index(a, x):
    i = bisect.bisect_left(a, x)
    return i
    
a = [1,2,4,5]
print(index(a, 6))
print(index(a, 3))


4
2


In [55]:
import queue
q = queue.Queue()
#insert items at the end of the queue 
for x in range(4):
    q.put(str(x))
#remove items from the head of the queue 
while not q.empty():
    print(q.get(), end=" ")
print("\n")


0 1 2 3 



In [56]:
def harmonic_sum(n):
  if n < 2:
    return 1
  else:
    return 1 / n + (harmonic_sum(n - 1))
    
print(harmonic_sum(7))
print(harmonic_sum(4))


2.5928571428571425
2.083333333333333


In [57]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [60]:
import numpy as np
# Create an empty array
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),6)
print(y)


[[9.91397793e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.46397805e-047 4.19241392e+175 2.83243639e-032]
 [2.05573632e+160 7.40331933e-038 9.51213020e+169 5.21734743e-037]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [61]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [62]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)


Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


In [63]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


In [64]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [65]:
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [66]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))


Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [67]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))


False
True
False
True


In [69]:
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))



False
True
True
True


In [70]:
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)


Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


In [71]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))


Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


In [72]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))


Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [73]:
import numpy as np
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)


Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


In [75]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)


[1 3 2 4 0]


In [76]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [77]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))


128 bytes


In [79]:
import numpy as np
print("Create an array of zeros")
x = np.zeros((1,2))
print("Default type is float")
print(x)
print("Type changes to int")
x = np.zeros((1,2), dtype = np.int)
print(x)
print("Create an array of ones")
y= np.ones((1,2)) 
print("Default type is float")
print(y)
print("Type changes to int")
y = np.ones((1,2), dtype = np.int)
print(y)


Create an array of zeros
Default type is float
[[0. 0.]]
Type changes to int
[[0 0]]
Create an array of ones
Default type is float
[[1. 1.]]
Type changes to int
[[1 1]]


In [80]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)


6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)


Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [82]:
import numpy as np
#using no.full
x = np.full((3, 5), 2, dtype=np.uint)
print(x)
#using no.ones
y = np.ones([3, 5], dtype=np.uint) *2
print(y)


[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [83]:
import numpy as np
x = np.eye(3)
print(x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [84]:
import numpy as np
x = np.arange(1, 15)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [2, 6]))


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [85]:
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))


Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [86]:
import numpy as np
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [88]:
import numpy as np
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)


[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]
